### ISSUE TITLE
cant get the plugin to work but docker works

### ISSUE THREAD

**Issue by Bretthansenpc** [jneilliii/OctoPrint-RTMPStreamer#2]
hello I love this plugin but i cant seem to get it to work with the start stop button it says its going but doesnt stream, when I click stop it shows an error saying theres no stream named that. 

although if I run the docker code it runs fine and streams any ideas?

**Comment by jneilliii** [comment]
What do you have as your webcam stream setting?  Because docker runs in it's own instance it has to be a hardcoded url so if you use something like the following it should work.  Once you change the webcam stream setting make sure to restart OctoPrint just to be safe.

```
http://192.168.0.2/webcam/?action=stream
```

**Comment by Bretthansenpc** [comment]
i have it hard coded in the rtmp tab does it need to be hard coded in the settings for the webcam itself?

**Comment by Bretthansenpc** [comment]
got it thanks!!!
