### ISSUE TITLE
Error while building docker

### ISSUE THREAD

**Issue by coolen555** [jneilliii/OctoPrint-RTMPStreamer#20]
Followed instructions but get this error everytime i try to build the docker image.
failed to register layer: Error processing tar file(exit status 1): unexpected EOF

**Comment by jneilliii** [comment]
You may want to try the webcamstreamer plugin, it's better than mine and has a docker image registered so easier to install.

**Comment by coolen555** [comment]
I tried that one but i only got a black screen when streaming. So far i haven't found a single working streaming plugin so i was hoping yours would work.

**Comment by jneilliii** [comment]
So you're getting the error when you run the line `docker build -t octoprint/rtmpstreamer .` Make sure you include the `.` at the end of the command line while in the rtmpstreamer folder.
