### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by RobinTail** [jneilliii/OctoPrint-RTMPStreamer#21]
Is it possible to add music or mixin a radio stream into the video stream?

**Comment by jneilliii** [comment]
It is possible by changing the audio input option in the docker's ffmpeg command. Might be easier to achieve with the webcam streamer plugin, as I think it has more options available via the web ui.

**Comment by RobinTail** [comment]
@jneilliii thank you so much for help

**Comment by RafaelDiasMoraes** [comment]
Could someone give me examples on how to do this?
I'm new with this and I want to add a backgroud music in my stream.
