### ISSUE TITLE
How to setup Youtube.

### ISSUE THREAD

**Issue by Stubbs** [jneilliii/OctoPrint-RTMPStreamer#22]
How are other people setting up their Youtube account to stream? Do you schedule a Live stream off in the future and set it to auto start/stop and just leave it or do you have to set up a new stream with fresh key each time you print?

**Comment by jneilliii** [comment]
You may want to look into the YouTube live plugin or webcamstreamer plugin. The plugin doesn't know of our care about scheduling, it just tries to stream.

**Comment by Stubbs** [comment]
Will do. I chose yours because it could do Twitch as well and I didn't know which I was going to use at the time.
