### ISSUE TITLE
404 Client Error: Not Found

### ISSUE THREAD

**Issue by epn35** [jneilliii/OctoPrint-RTMPStreamer#28]
Hello,
I have been confused for a few days with Docker. I'm trying to stream with "RTMP Streamer" or "WebcamStreamer" but it's the same problem: `<404 Client Error: Not Found ("pull access denied for adilinden / rpi-ffmpeg, repository does not exist or may require 'docker login ': denied: requested access to the resource is denied ")>`

![Sans titre-2](https://user-images.githubusercontent.com/80031126/109931637-62099d00-7cc9-11eb-885f-7b003a80ba1b.jpg)
![Sans-titre-3](https://user-images.githubusercontent.com/80031126/109931639-62a23380-7cc9-11eb-9c27-c8c1b9fa1c70.png)

Have you ever had this problem? Can you guide me to a solution, I don't know what to test anymore ..
I don't have proxy or something and i have corect link in webcam & Timelaps :/
Thank you.

**Comment by jneilliii** [comment]
I think you posted this on the wrong repo. You're using [YouTubeLive](https://github.com/jneilliii/OctoPrint-YouTubeLive), not RTMPStreamer it seems. I'll open a new issue over there for you.

**Comment by epn35** [comment]
The plugin is closed for YoutubeLive, can I restart the subject here?
I am trying to completely reinstall octoprint with only the RTMP plugin

**Comment by jneilliii** [comment]
Are you trying to stream to YouTube or Twitch/Other Service?

**Comment by epn35** [comment]
ok i have completely reinstall octoprint and install RTMP Streamer plugin.
First problem: `RTMP Streamer Error ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`
With correct Stream URL: http://192.168.1.10/webcam/?action=stream
And .... i try to reinstall WebcamStreamer because on option advanced i can change Docker Image and container name (picture).
![FireShot Capture 097 - OctoPrint - 192 168 1 10](https://user-images.githubusercontent.com/80031126/110211812-9f705500-7e98-11eb-8229-1409f462eb1c.png)
![FireShot Capture 100 - OctoPrint - 192 168 1 10](https://user-images.githubusercontent.com/80031126/110211816-a008eb80-7e98-11eb-9584-b2732a73c6f4.png)

i have install docker by Putty and add this:
`docker pull kolisko/rpi-ffmpeg`
I dont know if its correct or not iI didn't understand everything I was doing.
I have bad frame rate but, it's work !! :D 
i try to have a better frame rate later.. 
Thanks for the help anyway @jneilliii

**Comment by jneilliii** [comment]
Yeah, that's one of the reasons the webcamstreamer plugin is better than this one. It allows you to set the docker names versus being hardcoded in my plugin's.
