### ISSUE TITLE
Prereq error

### ISSUE THREAD

**Issue by nxvash** [jneilliii/OctoPrint-RTMPStreamer#31]
When I run the first command listed in the pre req instructions I get the following error: E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'

**Comment by jneilliii** [comment]
This has been happening for a lot of raspberry projects. Try running 
```
sudo apt update --allow-releaseinfo-change
```
