### ISSUE TITLE
RTMP Streamer Error

### ISSUE THREAD

**Issue by trojan-xs** [jneilliii/OctoPrint-RTMPStreamer#32]
I am terribly sleep deprived so I apologize in advance.
I am also a complete beginner to networking, docker and linux in general so I also apologize for that

### My Issue:

404 Client Error: Not Found ("No such container: 09c0e1d7e42992768535d11e6d92f486efb845bc215ba34ee91078a2c05780bb

![image](https://user-images.githubusercontent.com/49181542/145177223-163591a2-0255-44e5-8e95-00714e75ebce.png)

I followed all the steps from here: ["docker_isnstructions.md"](https://github.com/jneilliii/OctoPrint-RTMPStreamer/blob/master/docker_instructions.md)

### So here's what I've got:

![image](https://user-images.githubusercontent.com/49181542/145179644-3b037c16-0e7d-4278-8279-52be6773ff92.png)

`https://mydomain.com/webcam/?action=stream`
For obvious reasons, I have replaced my FQDN with "MYDOMAIN.com"

I know this works; I used the test tab and its totally fine

![image](https://user-images.githubusercontent.com/49181542/145177818-7ee92f74-eb67-45af-9bb8-5543f90c97b9.png)

It's a little cut off so here's my "View URL"
https://player.twitch.tv/?autoplay=false&channel=MYCHANNEL&parent=MYDOMAIN.com

Again, replaced my sensitive info here

Here's what happens:

When I press the start button, it just loads forever and my stream doesn't start

![image](https://user-images.githubusercontent.com/49181542/145178064-9959326e-6321-4d7b-a72b-e03993ca121c.png)

Untill I refresh the page, then it turns into a stop.

![image](https://user-images.githubusercontent.com/49181542/145178196-928e55ac-2fe6-4868-909d-7bddcddb4972.png)

Yet, my stream still isn't up

**Then when I press stop, this pops up:**

![image](https://user-images.githubusercontent.com/49181542/145178323-78d0198e-d11c-461d-b78d-6fb9cb5586b8.png)

`404 Client Error: Not Found ("No such container: 09c0e1d7e42992768535d11e6d92f486efb845bc215ba34ee91078a2c05780bb`

So I ran the test provided by  [docker_isnstructions.md](https://github.com/jneilliii/OctoPrint-RTMPStreamer/blob/master/docker_instructions.md)

I ran this in the terminal:
`docker run --privileged --name RTMPStreamer -ti octoprint/rtmpstreamer:latest https://MYDOMAIN.com/webcam/?action=stream 640x480 10 rtmp://live.twitch.tv/app/live_MYSTREAMKEY null `

And interestingly enough, it returns me this:

![image](https://user-images.githubusercontent.com/49181542/145178993-0fe6090d-e042-4c73-9476-bdc0c8ef6fa2.png)

But then when I run this: 
`docker run --privileged --name RTMPStreamer -ti octoprint/rtmpstreamer:latest http://192.168.1.111/webcam/?action=stream 640x480 10 rtmp://live.twitch.tv/app/live_MYSTREAMKEY null `
_192.168.1.111 is the private IP for my Pi_

The stream starts automatically.
But then when I press the stop stream button, the stream continues and this error pops up again:
![image](https://user-images.githubusercontent.com/49181542/145177223-163591a2-0255-44e5-8e95-00714e75ebce.png)
And the button does the same loading thing when I press start again.
The stream only stops when I give the kill signal command in the terminal.

**SIDENOTE:**
I am accessing the Octoprint web controls via my FQDN
When I access the Octoprint web controls via private ip {192.168.1.111) this sis what is shown on the "RTMP Streamer" tab
![image](https://user-images.githubusercontent.com/49181542/145181323-ab6c451a-5892-48f7-ba48-8fcd11c3187a.png)
`player.twitch.tv refused to connect`
Though this is a small issue compared to the error and the stream not working.

Really sorry if I did/said any really stupid stuff! I'm kind of a beginner.
Feel free to correct/guide me.

Thanks again

**Comment by jneilliii** [comment]
Ah, this looks like an underlying issue with the ffmpeg command that's being used in the docker container for streaming. I didn't make that underlying container so it's a matter of re-creating that container with https support option enabled. If you were to use regular http instead of https I bet it would work, but for obvious reasons (you're port forwarding) you wouldn't want to do that. If you can find an alternative docker container for ffmpeg that supports https and takes the commands the same way you could adjust the container used by this plugin to reference it instead, and I could assist you with what needs to be changed for that.

**Comment by trojan-xs** [comment]
I'm not quite sure I understand as I am unfamilliar with docker...
But what do you propose I do?

**Comment by jneilliii** [comment]
There will be a release in the near future that should make this process a little easier and removes the docker dependency as an option. I'll report back once those changes are received and merged.
