### ISSUE TITLE
MultiCam

### ISSUE THREAD

**Issue by mlee12382** [jneilliii/OctoPrint-RTMPStreamer#38]
Is it possible to get MultiCam plugin support for rtmpstreamer? It would be nice to be able to use a different camera than the primary camera for those of us that are using MultiCam.

**Comment by jneilliii** [comment]
You can do this by modifying the ffmpeg command under adcanced options, replacing the `{webcam_url}` token with the url for your secondary camera.

**Comment by mlee12382** [comment]
Sweet got it, I had to figure out what the proper formatting for the tokens was, it didn't want to save or even start the stream with the default settings and the primary camera. I was about to send a message asking for more help but figured I would try 1 more variation and it worked lol. Thanks for pointing me in the right direction! Cheers.

**Comment by mlee12382** [comment]
New issue, maybe I'm just missing something but when I reboot my pi the ffmpeg commands revert to default an no longer have my url saved?

**Comment by jneilliii** [comment]
separate bug report created.
