### ISSUE TITLE
when I reboot my pi the ffmpeg commands revert to default

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-RTMPStreamer#39]
New issue, maybe I'm just missing something but when I reboot my pi the ffmpeg commands revert to default an no longer have my url saved?

_Originally posted by @mlee12382 in https://github.com/jneilliii/OctoPrint-RTMPStreamer/issues/38#issuecomment-1025054905_

**Comment by mlee12382** [comment]
Where do the files install on the pi? I can just manually edit it in nano via ssh as a temporary fix?

**Comment by jneilliii** [comment]
I'm not sure setting it manually will make a difference. I need to make adjustments to the code. I'll take a look tonight and see if there is a quick fix.

**Comment by jneilliii** [comment]
Fixed with the above commit and will be released shortly as version 1.0.2.

**Comment by mlee12382** [comment]
Awesome thanks for the assistance  :)
