### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by Eruditionis** [jneilliii/OctoPrint-RTMPStreamer#44]
I wasn't getting the plugin to work through octoprint, after emailing Jneilliii I figured out docker was my issue. Now, when I enable the stream through docker, I get enough to start the stream via YouTubeLive, but it's only a snapshot. I get no video.

I am using FFmpeg for streaming, settings/fails in pics
![fail 5](https://user-images.githubusercontent.com/101606579/158278173-af4fc2b7-29ca-49ab-9e03-a1859ce207f6.PNG)
![Fail 4](https://user-images.githubusercontent.com/101606579/158278176-980f3223-0bba-4cd7-8939-95f52096e26c.PNG)
![Fail 3](https://user-images.githubusercontent.com/101606579/158278177-068a6225-f5ed-497e-9974-34d9522cef82.PNG)
![fail 2](https://user-images.githubusercontent.com/101606579/158278179-eb2d7b58-adf2-4397-ba96-66765d3e7118.PNG)
![fail](https://user-images.githubusercontent.com/101606579/158278180-dba4dc0c-1e9e-4a22-a513-d734d1e91bc1.PNG)

When I used docker I could get test video, but no output from the plugin, now that docker is gone, I have output from the plugin, but no video :/

**Comment by jneilliii** [comment]
enable the option for ffmpeg debug and attempt to start the stream. this will give more detailed error messages from the ffmpeg command it's own logging file in the logging section of OctoPrint.

**Comment by Eruditionis** [comment]
Done, I got video but it is giving me an error saying there isn't enough of
it being sent to maintain a smooth stream. It is buffering for a minute
then has sped up video, also appears to be stretched out as seen if you
click this link <https://youtu.be/vQ8fdBm6qXY>, hopefully it's still going
when you get this. I will also link the rtmpstreamer log below for you in
case it helps?

**Comment by TheSin-** [comment]
The stretch is cause you aren't setting the size to the aspect of your camera, make sure you know the natural aspect of your cam when you set the stream size.

As for buffering remember you're limited by hardware or network if you're on a Pi via Wifi, that's some heavy restrictions and YouTube requires a very heavy stream to be happy.

Thought honestly your stream looks really good

![Screen Shot 2022-03-15 at 8 08 30 AM](https://user-images.githubusercontent.com/1868661/158396009-db40db12-4605-4620-95d8-8841cd141bc1.png)

**Comment by Eruditionis** [comment]
Maybe it's me being very picky, I appreciate it! How do I tell the size of
my camera? Some streams come out good, some are stretched. Maybe just
restart it until it works?

**Comment by Eruditionis** [comment]
Also, I am using a Ethernet cable, before I got flawless videos(just a little grainy), but I have been streaming for 40 minutes and only have about 15 minutes worth of video

**Comment by TheSin-** [comment]
I'm doing more work on the setup to enable HW encoders which will help a lot.  Right now it's using SW encoders.

As for video size are you on a Pi?

**Comment by Eruditionis** [comment]
Yes, I have a rpi 4B with this camera
<https://www.amazon.com/Raspberry-Camera-Webcam-OV5647-Adjustment/dp/B08QFM8TVV/ref=sr_1_5?crid=Z3040ITF7LEX&keywords=camera+raspberry+pi&qid=1647354231&sprefix=camera+raspberry+pi%2Caps%2C64&sr=8-5>

**Comment by TheSin-** [comment]
When I set mine up I use this chart if using a pi with picamera

https://picamera.readthedocs.io/en/release-1.12/fov.html

then you setup the octopi.txt file in /boot to have the same settings that you want form that chart.  And in rmtpstreamer make sure you use the same settings.

**Comment by TheSin-** [comment]
make sure you give yourself enough gpu_mem in config.txt as well as this is very gpu intense

**Comment by Eruditionis** [comment]
So should I ssh into the pi to change that value? How much should I give for reference? I'm very new to this

**Comment by TheSin-** [comment]
There are soooo many factors to answer that, I'd start with 128 and move up from there.

**Comment by Eruditionis** [comment]
I have 128 automatically assigned, so I will bump it up to 256

**Comment by jneilliii** [comment]
I think 256 is what I typically put in that setting.

**Comment by Eruditionis** [comment]
Okay, I just changed the setting, I will sudo reboot my pi when it is done
with it's current print job. Will update as soon as possible!

**Comment by Eruditionis** [comment]
256 yields the same results, should I bump it up again? For 2 min of stream time, only <15 seconds of footage was sent out

**Comment by Eruditionis** [comment]
![ffmpg](https://user-images.githubusercontent.com/101606579/158591842-93eda9ba-95c4-4e50-8e9e-897a84051f72.PNG)

**Comment by TheSin-** [comment]
turn off the overlay, it will slow things down as it needs to process each frame, see if that helps.

**Comment by Eruditionis** [comment]
The overlay is off, restarted live stream, no overlay in the video, but the output is still just as bad. If I hadn't had really good streams just a week ago, I would guess my wifi is bad, but I had really good streams on this wifi not long ago

**Comment by TheSin-** [comment]
what are you setting your bitrate to? the default is 700k and that is really small for YouTube, I forget all the info but they have a help page listing what it should be based on stream res

**Comment by TheSin-** [comment]
Remember the plug just gives you the tools, the setup might need to be googled a bit, I'm no pro with YouTube I found it to be very difficult and lacking so I use Twitch.

**Comment by Eruditionis** [comment]
i'm not sure where to find the bitrate to change that, is it in one of the config files? Or can I find it in octoprint?

Could very well be Youtube, I am going to try it on Facebook, and if no beans there then I will use twitch.

**Comment by Eruditionis** [comment]
My guess is that the bitrate is 700, because I have no idea where it is so no changes to it

**Comment by TheSin-** [comment]
it's in the advanced features under ffmpeg in the plugin config.

I'd post a screen shot but don't have onto at work ;)

**Comment by Eruditionis** [comment]
That's fine, I am also at work lol, that's the only time I have access to the printer (I work at a library)

I will see if I can change that, should I change anything else in that area? I notice there are a bunch of options labeled for experts only

**Comment by TheSin-** [comment]
It's there for those that know ffmpeg to have more granular control.  So feel free but I'd read first ;)

The big thing with YouTube is getting the amount of data it wants, that being said the old version of the plugin was using 700k as well, none of that changed, the big change with the overlay, which is why I suggested we remove it.  Since it's acting the same I'm very curious what the issue is, I just don't know enough about YouTube but I know it's been a pain.

I plan to work more on the plugin very soon I'll try and focus some attention on YouTube maybe I can change some default settings if it's set to YouTube if Ic an find what the issue with it is.

**Comment by Eruditionis** [comment]
Okay, so I just changed the setting to Youtube's recommended bitrate of 4500K and still have buffering. Funny enough it is actually much worse now...

Yeah I can try other ways to stream, our thing is to provide our patrons with the ability to watch their prints as they progress, so it doesn't matter where it streams to as long as it streams lol.

I really appreciate all this help though, I do plan on contributing to the plugin, this is one of my most used plugins

**Comment by TheSin-** [comment]
https://support.google.com/youtube/answer/2853702?hl=en

**Comment by TheSin-** [comment]
looks like they want keyframes which I'm not setting in the plugin give me a few minutes to hash out the string of it and I'll send you something to try.

**Comment by Eruditionis** [comment]
Okay that works! Thank you so much for all of this

**Comment by TheSin-** [comment]
in the experimental

can you try to replace this part `-vb {bitrate}` with `-b:v {bitrate} -maxrate {bitrate} -minrate {bitrate} -bufsize {bitrate}`

Remember if you make changes there when a new version is released it won't change that, you'll need to remember to click the resend button on that filed to reset it.  And this is just a test, I can't test it currently :)

**Comment by Eruditionis** [comment]
Should I reboot the rpi once making that change? I added that line in and pressed save

**Comment by TheSin-** [comment]
no saving and restarting the stream is good enough

**Comment by Eruditionis** [comment]
Okay, got it, gonna start up the stream again and update in a minute or two

**Comment by Eruditionis** [comment]
So I am getting the same issue, buffering with 1-3 seconds of video in between buffers. 

I had this set up to run through docker before and had the video running, only issue was that I couldn't start the stream through the plugin. Do you think that route would be easier or should we stick with this?

**Comment by TheSin-** [comment]
docker would add a layer, the only difference would be the string that starts ffmpeg if you can extract what you had for your string I could tell you how to setup the plugin to work the same.

**Comment by Eruditionis** [comment]
I'm not sure if this detail matters, but when I do get video, it's very sped up.

**Comment by TheSin-** [comment]
it's just catching up, it's using UDP so there is no frame order.

**Comment by TheSin-** [comment]
what docker image were you using before I'll have a look at it and extract how it was running ffmpeg for you.

**Comment by Eruditionis** [comment]
How would I extract that? I believe it was the most recent one, using the directions in the prerequisites link on the setup page

**Comment by Eruditionis** [comment]
Just checked, I didn't reinstall docker since I reimaged the pi, will install now and update in a few mins

**Comment by TheSin-** [comment]
one sec I'll check the docs

**Comment by TheSin-** [comment]
this is the image, and the command is at the bottom of the page

https://hub.docker.com/r/kolisko/rpi-ffmpeg

**Comment by TheSin-** [comment]
reset the ffmpeg command first then

try to replace `{videocodec}` with `h264`

**Comment by Eruditionis** [comment]
Server: Docker Engine - Community
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:46 2022
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by Eruditionis** [comment]
I finished installing docker, I also had it pull kolisko/rpi-ffmpeg:latest

**Comment by Eruditionis** [comment]
How do I reset the ffmpeg command? 

I replaced that.

When I put that command in, I get this: (I didn't leave the xxxx-xxxx's in there)

` docker run -it --rm --privileged adilinden/ffmpeg ffmpeg \ -re -f mjpeg -framerate 5 -i http://192.168.1.16:8080/?action=stream \ -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -acodec aac -ab 128k \ -strict experimental -vcodec h264 -pix_fmt yuv420p -g 10 -vb 700k -framerate 5 \ -f flv rtmp://a.rtmp.youtube.com/live2/xxxx-xxxx-xxxx-xxxx-xxxx
Unable to find image 'adilinden/ffmpeg:latest' locally
docker: Error response from daemon: pull access denied for adilinden/ffmpeg, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

**Comment by TheSin-** [comment]
you can't replace it with that.

there is a button right beside the title.  Also if you ran that you'll need to reboot now.

**Comment by Eruditionis** [comment]
I just rebooted the pi, I thought it failed when I tried running that command? 

I meant that I replaced the  {videocodec} with h264

**Comment by TheSin-** [comment]
that's cause you are running it with docker, don't use docker.

**Comment by Eruditionis** [comment]
Okay, I’ll shut off docker my bad, will run again when I’m back at work
tomorrow and let you know ツ

**Comment by jneilliii** [comment]
not sure how tight your library's network is, but you might want to look into something like tailscale to be able to remote access to your pi/OctoPrint remotely. You basically install on the pi and then install on whatever device you want to be able to access it from and it will establish a connection between the two. I've used it in the past and it was pretty easy to setup. Another option if you only need to access OP is OctoEverywhere plugin.

**Comment by Eruditionis** [comment]
I just got the octoeverywhere plugin, all set up to go so I can change op settings from wherever. Can I use that tailscale program to perform ssh functions from home too?

**Comment by Eruditionis** [comment]
I don't have docker checked, I can't get any video to go through now :( 


Should I remove docker from the pi?

**Comment by Eruditionis** [comment]
Weirdly enough, I can't do those commands, they all ask for a password, when I do type it in they tell me I cannot use that type of verification anymore,

Furthermore, when I use the [link provided](https://github.com/adilinden-oss/docker-ffmpeg.git), they do not exist anymore

**Comment by jneilliii** [comment]
Yes, tailscale is like a VPN solution that will allow you to do anything with the pi, including ssh. You just have to utilize the pi's tailscale ip instead of the local network one.

**Comment by Eruditionis** [comment]
Oh okay cool, i'm definitely gonna look into that!

**Comment by Eruditionis** [comment]
I ended up getting a streaming software and inputting everything manually. Thus I do not require the plugin anymore, as an added bonus I get sound to the background of my stream and better quality. Thank you very much for your help!
