### ISSUE TITLE
How to use secondary cam for stream

### ISSUE THREAD

**Issue by Mackalope** [jneilliii/OctoPrint-RTMPStreamer#47]
How does one change the URL to find second cam under port 8081?

**Comment by jneilliii** [comment]
you would hvae to go into advanced options on the ffmpeg tab and replace the `{webcam_url}` token with the url for your second camera.

![image](https://user-images.githubusercontent.com/5249455/210023693-e11a4ef4-f6a5-43cd-8bdd-431d7e2a6ef6.png)

**Comment by Mackalope** [comment]
Awesome, thank you.
