### ISSUE TITLE
Feature request: stats overlay

### ISSUE THREAD

**Issue by Obliterous** [jneilliii/OctoPrint-RTMPStreamer#54]
Request: Can a feature be added to add temp/time overlays as well as configurable text and image overlays?

**Comment by jneilliii** [comment]
You mean like the dynamic overlay settings with text substitutions?

![image](https://github.com/jneilliii/OctoPrint-RTMPStreamer/assets/5249455/866ab9ab-8849-4cd5-b888-a7e63394f76d)

**Comment by TheSin-** [comment]
I love this feature ;) though I'm bias ;)
