### ISSUE TITLE
A way to rotate video before streaming ?

### ISSUE THREAD

**Issue by tavdog** [jneilliii/OctoPrint-RTMPStreamer#55]
I would like to rotate the video as my camera is at 90 degrees. I can't figure out a way to rotate it. Maybe with the ffmpeg command ?

**Comment by jneilliii** [comment]
Yeah, you should be able to achieve that with vfilters (-vf) command I think. Quick search seems to indicate you need `-vf "transpose=1"`

For the transpose parameter you can pass:

0 = 90° counterclockwise and vertical flip (default)
1 = 90° clockwise
2 = 90° counterclockwise
3 = 90° clockwise and vertical flip

**Comment by tavdog** [comment]
Yes! This worked.  Here is my updated ffmpeg command
`{ffmpeg} -re -f mjpeg -framerate {frame_rate} -i {webcam_url} {filter} -f lavfi -i anullsrc -acodec aac -ab 128k -s {stream_resolution} -vcodec {videocodec} -threads {threads} -pix_fmt yuv420p -framerate {frame_rate} -vf "transpose=1" -g {gop_size} -vb {bitrate} -strict experimental -f flv {stream_url}`

**Comment by tavdog** [comment]
It does work but now the image is squashed.  . . . oh nevermind, just had to change the stream resolution. to 480x640

**Comment by jneilliii** [comment]
@TheSin- you maybe have any ideas about the best way to rotate?

**Comment by TheSin-** [comment]
I would have thought the same though I would have though 3 not 1.

That being said does the input and output match in res? it's odd that it's squashing it.

**Comment by tavdog** [comment]
Setting the resolution to be 480x640 unsquashes it.

**Comment by TheSin-** [comment]
so it's working then?

**Comment by tavdog** [comment]
Yes it's working now.

**Comment by TheSin-** [comment]
excellent, happy to hear it.
