### ISSUE TITLE
Howto separate url and key 

### ISSUE THREAD

**Issue by sprucify** [jneilliii/OctoPrint-RTMPStreamer#6]
I'm just curious if there is a way to fill in the url and key separately?
All other platforms give a RTMP url and a key.
Do you concatenate them with a underscore?

**Comment by jneilliii** [comment]
In its current implementation no, there is no way to have the two separate. My thought was they always get put into a full url anyway, and by entering the full url there is the most flexibility of where the key goes within that url. If I were to concentrate programmaticaly it may not be possible to match all possible options.
